### PR TITLE
Fix: EnumTransformer properly handling single-quotes in backed enum string values

### LINKED ISSUE #99: String-backed enum cases that have single-quotes break TS unions
## Description 

The enum generated uses single-quotes as the string delimiter, but doesn't escape any single quotes inside the value of the case. This might be the case with native TS enums as well, but I do not use native enums in my TS code.

### Desired functionality

```ts
export type properEnumUnion = 'Bachelor\'s degree' | 'Associate\'s degree';
```

### Current functionality

```ts
export type brokenEnumUnion = 'Bachelor's degree' | 'Associate's degree';
```

### PR DESCRIPTION
**Pull request by sugarmaplemedia**
closes #99 

Sorry if I missed anything in this pull request, this is my first contribution to an open-source project. :)

I modified the EnumTransformer's `toEnumValue` method so it looks at each character individually in case it needs to add something different to the string for it to work in TS. This way, in can be extended more easily for broken characters in the future.

### CODE REVIEW

File: src/Transformers/EnumTransformer.php [hunk 1]
```diff
@@ -73,6 +73,22 @@ protected function toEnumValue(ReflectionEnumBackedCase $case): string
...
+        }
+
+        for ($i = 0; $i < strlen($value); $i++) {
+            $char = $value[$i];
+
+            match ($char) {
+                '\\' => $newValue .= '\\\\',
+                '\'' => $newValue .= '\\\'',
+                default => $newValue .= $char,
+            };
```
Comment (jdreesen) [inline src/Transformers/EnumTransformer.php:89]:
```suggestion
            $newValue .= match ($char) {
                '\\' => '\\\\',
                '\'' => '\\\'',
                default => $char,
            };
```
